server:
  port: 27015
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: OneSpring
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:h2:mem:onespring
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jdbc:
    template:
      query-timeout: 30000
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG